# rdoinfo configs
artg_skipped_projects:
  - rdoinfo
update_containers: false
docker_registry_host: "{{ push_registry | default('127.0.0.1:8787') }}"
standalone_container_prep_updates: false

# name and tags
devmode: true
overcloud_as_undercloud: true
release: ussuri
distro_ver: centos8
distro_deps_repo_name: deps
dlrn_hash_tag: current-tripleo
dlrn_hash_tag_newest: current
docker_registry_namespace: "tripleo{{ release }}"
docker_image_tag: "cloudsig-{{ release }}"
docker_openshift_tag: v3.11.0
promote_source: current-tripleo
validate_on: rdo

# images
images:
  - name: overcloud-full
    url: "{{ overcloud_image_url }}"
    type: tar
  - name: ipa_images
    url: "{{ ipa_image_url }}"
    type: tar
inject_images:
  - "ironic-python-agent.initramfs"
  - "ironic-python-agent.kernel"
  - "overcloud-full.qcow2"
  - "overcloud-full.initrd"
  - "overcloud-full.vmlinuz"

dlrn_baseurl: "https://trunk.rdoproject.org/{{ distro_ver }}-{{ release }}"
overcloud_image_url: "https://images.rdoproject.org/{{ distro_ver }}/{{ release }}/rdo_trunk/{{ promote_source }}/overcloud-full.tar"
ipa_image_url: "https://images.rdoproject.org/{{ distro_ver }}/{{ release }}/rdo_trunk/{{ promote_source }}/ironic-python-agent.tar"

# repo setup
repo_cmd_before: |
  sudo rm -rf /etc/yum.repos.d/delorean*;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo rm -rf /etc/yum.repos.d/epel*;
  sudo dnf remove -y rdo-release centos-release-ceph-* centos-release-openstack-* centos-release-qemu-ev || true;
  sudo rm -rf /etc/yum.repos.d/CentOS-OpenStack-*.repo /etc/yum.repos.d/CentOS-Ceph-*.repo /etc/yum.repos.d/CentOS-QEMU-EV.repo;

  sudo dnf clean all;
  sudo dnf config-manager --disable "*" || true;
  if [ -e /etc/ci/mirror_info.sh ]; then
    source /etc/ci/mirror_info.sh
  else
    # Otherwise, fallback to official mirrors provided by CentOS.
    export NODEPOOL_CENTOS_MIRROR={{ lookup('env','NODEPOOL_CENTOS_MIRROR')|default('http://mirror.centos.org/centos', true) }}
    export NODEPOOL_RDO_PROXY=https://trunk.rdoproject.org
  fi

repos:
  - type: package
    pkg_name: "centos-release-openstack-{{ release }}"
    custom_cmd: 'sudo dnf install -y --enablerepo=extras'

  # Needed for mock installation
  - type: generic
    reponame: "delorean-{{ release }}-build-deps"
    filename: "delorean-{{ release }}-build-deps.repo"
    baseurl: "${NODEPOOL_RDO_PROXY}/{{ distro_ver }}-{{ release }}/build-deps/latest/"

  # CentOS related repos
  - type: generic
    reponame: quickstart-centos-base
    filename: quickstart-centos-base.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8-stream/BaseOS/x86_64/os/

  - type: generic
    reponame: quickstart-centos-appstreams
    filename: quickstart-centos-appstreams.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8-stream/AppStream/x86_64/os/

  - type: generic
    reponame: quickstart-centos-powertools
    filename: quickstart-centos-powertools.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8-stream/PowerTools/x86_64/os/

  - type: generic
    reponame: quickstart-centos-highavailability
    filename: quickstart-centos-highavailability.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8-stream/HighAvailability/x86_64/os/

  - type: generic
    reponame: quickstart-centos-extras
    filename: quickstart-centos-extras.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8-stream/extras/x86_64/os/

  - type: generic
    reponame: quickstart-centos-ceph-nautilus
    filename: quickstart-centos-ceph-nautilus.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8/storage/x86_64/ceph-nautilus/

  - type: generic
    reponame: quickstart-centos-opstools
    filename: quickstart-centos-opstools.repo
    baseurl: ${NODEPOOL_CENTOS_MIRROR}/8/opstools/x86_64/collectd-5/

repo_cmd_after: |
  {% if not enable_opstools_repo|default(false)|bool %}sudo yum-config-manager --save --setopt quickstart-centos-opstools.enabled=0;
  {%endif %}
  # sudo dnf config-manager --disable rdo-qemu-ev;
  sudo rpm -e epel-release || true;
  sudo dnf remove -y rdo-release || true;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  sudo dnf repolist;
  sudo dnf module list;
  sudo dnf module disable container-tools:rhel8 -y;
  sudo dnf module enable container-tools:2.0 -y;
  sudo dnf clean metadata
  {% if repo_setup_run_update|default(true)|bool %}
  sudo dnf update -y
  {% endif %}

undercloud_rpm_dependencies: >-
  python3-tripleoclient
  ceph-ansible

# baseos settings
baseos_undercloud_image_url: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20201217.0.x86_64.qcow2
baseos_image: centos
baseos_image_type: qcow2
baseos_md5sum: "70d5c374156f2ab92c058b6a6150f55e  CentOS-Stream-GenericCloud-8-20201217.0.x86_64.qcow2"
