##################################################
# FEATURESET060 - TRIPLEO STANDALONE with IRONIC
##################################################

non_root_user_setup: true
ovb_setup_connectivity: false
package_installs: true
vxlan_networking: false
toci_vxlan_networking: false
enable_vbmc: false
deploy_supplemental_node: false
undercloud_setup: true

# role / scenario definition
# deployment role
standalone_role: Standalone.yaml
ironic_overcloud: true

# custom env files
standalone_custom_env_files:
  - /usr/share/openstack-tripleo-heat-templates/environments/low-memory-usage.yaml

# validation

test_ping: false
use_os_tempest: true
# NOTE(aschultz): containers assume RC at the moment
tempest_undercloud: true
tempest_overcloud: false
tempest_services:
  - neutron
  - ironic
tempest_tempestconf_profile_overrides:
  auth.create_isolated_networks: 'False'
  validation.connect_method: 'fixed'
  validation.network_for_ssh: 'provisioning'
  baremetal.use_provision_network: 'True'

tempest_run_concurrency: 2
tempest_os_cloud: standalone
tempest_public_net_name: "provisioning"
tempest_public_subnet_name: "provision-subnet"
tempest_private_net_seg_id: ''
tempest_test_whitelist:
  - 'ironic_tempest_plugin.tests.api.admin.test_chassis.TestChassis'
  - 'ironic_tempest_plugin.tests.api.admin.test_api_discovery.TestApiDiscovery'
  - 'ironic_tempest_plugin.tests.api.admin.test_conductor.TestConductors'
  - 'ironic_tempest_plugin.tests.api.admin.test_deploy_templates.TestDeployTemplates'
  - 'ironic_tempest_plugin.tests.api.admin.test_deploy_templates.TestDeployTemplatesNegative'
  - 'ironic_tempest_plugin.tests.api.admin.test_deploy_templates.TestDeployTemplatesOldAPI'

standalone_container_cli: podman
