# Run an undercloud without glance or nova
undercloud_enable_nova: >-
  {% if release in ['newton','ocata','pike','queens','stein', 'train'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
step_glance_upload: >-
  {% if release in ['newton','ocata','pike','queens','stein', 'train'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

# general multinode job configuration
enable_vbmc: false
gating_repo_enabled: true
deploy_multinode: true
step_overcloud_image: false
step_register: false
hypervisor_wait: false
network_isolation: false
package_installs: true
non_root_user_setup: true
