composable_scenario: multinode-containers.yaml
composable_services: false

network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false
containerized_overcloud: true

containerized_undercloud: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

undercloud_templates_path: /usr/share/openstack-tripleo-heat-templates
undercloud_custom_env_files: "{{ working_dir }}/undercloud-parameter-defaults.yaml"
undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

deployed_server: >-
  {% if release in ['newton','ocata','pike'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
deploy_steps_ansible_workflow: >-
  {% if release not in ['newton','ocata','pike'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
config_download_args: >-
  {% if release in ['queens'] -%}
  -e /usr/share/openstack-tripleo-heat-templates/environments/config-download-environment.yaml
  --config-download
  --deployed-server
  {%- endif %}
  {% if release not in ['newton','ocata','pike'] -%}
  -e {{ working_dir }}/config-download.yaml
  --disable-validations
  {%- endif -%}

# Tempest configuration, keep always at the end of the file
test_ping: false

# Settings for os_tempest

use_os_tempest: >-
  {% if release not in ['pike', 'queens', 'stein'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

tempest_test_whitelist:
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps'

test_white_regex: 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'

# https://launchpad.net/bugs/1844446
undercloud_enable_validations: false

undercloud_enable_paunch: false
