##################################################
# FEATURESET050 - CONTAINERIZED UNDERCLOUD UPGRADE
# Based on featureset047
##################################################

ssl_overcloud: false
undercloud_check_sanity: true
undercloud_upgrade_cleanup: true

containerized_undercloud: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

containerized_overcloud: >-
  {% if release in ['newton', 'ocata', 'pike'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

containerized_overcloud_upgrade: false
containerized_undercloud_upgrade: true

undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"

# Tripleo-upgrade specific parameters
undercloud_upgrade: true
tripleo_ci: true
use_oooq: true

# Deactivate validations as there is no overcloud
use_os_tempest: false
test_ping: false

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: true
undercloud_enable_swift_encryption: true

# There is not enough space in the Undercloud <20GB
undercloud_enable_validations: false

undercloud_enable_paunch: false
