# Summary of the feature set.
# Deploy a containerized Openstack environment using the keystone-only
# scenario (scenario000) and upgrade it

undercloud_setup: true
overcloud_ipv6: false
network_isolation: false
enable_pacemaker: false

# Container prep parameters.
containerized_overcloud: true
containerized_overcloud_upgrade: true
# mixed_upgrade, used for a mixed initial deployment of undercloud and overcloud releases
mixed_upgrade: false
# noop_upgrade, used when running upgrades from $release to $release
noop_upgrade: true

enable_opstools_repo: true

undercloud_generate_service_certificate: false

ssl_overcloud: false

step_introspect: false

composable_scenario: scenario000-multinode-containers.yaml
upgrade_composable_scenario: scenario000-multinode-containers.yaml
deployed_server: true

test_ping: false
use_os_tempest: false

# Tripleo-upgrade role parameters
# Major Upgrade: containers -> containers (keystone-only)
overcloud_upgrade: true
# This featureset is a master to master job, so we don't want to update the
# repo during the upgrade run
update_repo: false
# disable tripleo-upgrade container manipulation.
create_docker_registry: false
use_local_docker_registry: false
create_container_images_download_script: false

# do not run workload test
launch_sanity_workload: false

# container_registry_file is used pre-rocky, after rocky
# is uc_containers_prepare_file the one used to identify
# the containers file (defaults to: containers-prepare-parameter.yaml)
container_registry_file: containers-default-parameters.yaml
tripleo_ci: true
use_oooq: true
tripleo_upgrade_debug: false
overcloud_ssh_user: >-
  {% if release in ['queens'] -%}
  "tripleo-admin"
  {%- else -%}
  "zuul"
  {%- endif -%}

# Mandatory for deployed_servers
tripleo_upgrade_validations_non_fatal: true

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate

composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant


deploy_steps_ansible_workflow: true
config_download_args: >-
  {% if release in ['queens'] -%}
  -e /usr/share/openstack-tripleo-heat-templates/environments/config-download-environment.yaml
  --config-download
  --deployed-server
  {%- endif %}
  {% if release not in ['newton','ocata','pike'] -%}
  -e {{ working_dir }}/config-download.yaml
  --disable-validations
  --verbose
  {%- endif -%}

containerized_undercloud: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

undercloud_templates_path: /usr/share/openstack-tripleo-heat-templates
undercloud_custom_env_files: "{{ working_dir }}/undercloud-parameter-defaults.yaml"
undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"
ctlplane_masquerade: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
