undercloud_generate_service_certificate: false

# pacemaker settings are configured in the scenario template
# do not set `enable_pacemaker` in the featureset

deployed_server: true
composable_scenario: scenario003-multinode.yaml
validate_template: scenario003-multinode.yaml
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

# Tempest configuration, keep always at the end of the file
# Use the traditional ping test in newton and ocata
# Run tempest in pike+

test_ping: >-
  {% if release in ['newton', 'ocata'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

test_white_regex: ''
tempest_whitelist:
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'
  - 'sahara_tempest_plugin.tests.api.test_data_sources.DataSourceTest'
  - 'mistral_tempest_tests.tests.api.v2.test_actions.ActionTestsV2'
tempest_plugins_old:
  - python-sahara-tests-tempest
  - python-mistral-tests
tempest_plugins_new:
  - python-sahara-tests-tempest
  - python-mistral-tests-tempest

tempest_plugins: >-
  {% if release not in ['newton', 'ocata', 'pike'] -%}{{ tempest_plugins_new }}
  {%- else -%}{{ tempest_plugins_old }}
  {%- endif -%}
