# Deploy minimal overcloud (keystone and supporting services) and run
# a minor version update (overcloud only).

composable_scenario: scenario000-multinode-containers.yaml

# Tripleo-upgrade role parameters
# Minor Update
overcloud_update: true
# NOTE: right now the container images stay the same before and
# after update. This makes the job run fast while still testing
# the update workflow itself. For the future we may consider
# updating the container images too. (This might have to be paired
# with some work on the image building side to get meaningful
# from-to combination of images.
container_registry_file: >-
  {% if release not in ['queens','stein'] -%}
  ''
  {%- else -%}
  containers-default-parameters.yaml
  {%- endif -%}

tripleo_upgrade_validations_non_fatal: true
tripleo_upgrade_debug: false
tripleo_ci: true
use_oooq: true
overcloud_ssh_user: >-
  {% if release in ['queens'] -%}
  "tripleo-admin"
  {%- else -%}
  "zuul"
  {%- endif -%}

network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false
containerized_overcloud: true

undercloud_generate_service_certificate: false
ssl_overcloud: false

# extra testing disabled for now, may be enabled later depending on
# job run time
test_ping: false
use_os_tempest: false
# test_white_regex: 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'

composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

deploy_steps_ansible_workflow: true
config_download_args: >-
  {% if release in ['queens'] -%}
  -e /usr/share/openstack-tripleo-heat-templates/environments/config-download-environment.yaml
  --config-download
  --deployed-server
  {%- endif %}
  {% if release not in ['newton','ocata','pike'] -%}
  -e {{ working_dir }}/config-download.yaml
  --disable-validations
  --verbose
  {%- endif -%}

containerized_undercloud: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

undercloud_templates_path: /usr/share/openstack-tripleo-heat-templates
undercloud_custom_env_files: "{{ working_dir }}/undercloud-parameter-defaults.yaml"
undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"
ctlplane_masquerade: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

ephemeral_heat: "{{ (release not in ['queens', 'stein','train','ussuri','victoria']) | bool }}"
ephemeral_heat_args: "{{ '--heat-type pod' if ephemeral_heat|bool else '' }}"
