# EXPERIMENTAL FEATURE

# Tell tripleo how we want things done.
# Note: The order of the templates and arguments passed to heat matters.

extra_args: ''

network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false
undercloud_check_sanity: true

# containers config
containerized_overcloud: false
containerized_undercloud: true
undercloud_templates_path: /usr/share/openstack-tripleo-heat-templates
undercloud_custom_env_files: "{{ working_dir }}/undercloud-parameter-defaults.yaml"
# Prevent regression as described in https://bugs.launchpad.net/tripleo/+bug/1869360
undercloud_cloud_domain: "localDomain"
undercloud_undercloud_hostname: "underCloud.{{ undercloud_cloud_domain }}"
undercloud_undercloud_public_host: "{{ ansible_hostname }}-unique"
tripleo_set_unique_hostname: true

# turn off image prep
step_overcloud_image: false
step_glance_upload: false
step_register: false
step_root_device_size: false
step_root_device_hints: false
step_introspect: false

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: true
undercloud_enable_swift_encryption: true

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

# tripleo-ui is not working yet
enable_port_forward_for_tripleo_ui: false

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-deploy
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - tempest-setup

  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-deploy
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - tempest-setup

# Tempest configuration, keep always at the end of the file
test_ping: false
# os_tempest configuration

use_os_tempest: >-
  {% if release not in ['pike', 'queens', 'stein'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

tempest_install_method: distro
tempest_cloud_name: 'undercloud'
# There is no external network used for so disabling neutron
tempest_service_available_neutron: false

tempest_test_whitelist: "{{ tempest_whitelist }}"
tempest_test_blacklist: "{{ test_black_regex }}"
test_regex: ''

# Run an undercloud without glance or nova
undercloud_enable_nova: >-
  {% if release in ['newton','ocata','pike','queens','stein','train'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

# Enable mistral tempest plugin
tempest_service_available_mistral: >-
   {% if lookup('env', 'ZUUL_PROJECT') == "openstack/mistral" -%}
   true
   {%- endif -%}

tempest_undercloud: true
tempest_overcloud: false
tempest_whitelist: >-
   {% if lookup('env', 'ZUUL_PROJECT') == "openstack/mistral" -%}
   {{ tempest_whitelist_mistral }}
   {%- else -%}
   {{ tempest_whitelist_uc }}
   {%- endif -%}

# default tempest tests for UC
tempest_whitelist_uc:
  - 'tempest.api.identity'
  - 'tempest.api.network.test_networks'
  - 'tempest.api.network.test_networks_negative'
  - 'tempest.api.network.test_security_groups_negative'
  - 'tempest.api.network.test_ports'
  - 'tempest.api.network.test_routers_negative'

# tempest tests for Mistral
tempest_whitelist_mistral:
  - 'mistral_tempest_tests'

test_black_regex: >-
   {% if lookup('env', 'ZUUL_PROJECT') == "openstack/mistral" -%}
   {{ mistral_test_black_regex }}
   {%- endif -%}

# skip list for mistral tempest plugin
mistral_test_black_regex:
  - 'mistral_tempest_tests.tests.scenario.engine.actions.v2.test_openstack_actions.OpenStackActionsTestsV2.test_cinder_actions'
  - 'mistral_tempest_tests.tests.scenario.engine.actions.v2.test_ssh_actions.SSHActionsTestsV2.test_run_ssh_action'
  - 'mistral_tempest_tests.tests.scenario.engine.actions.v2.test_ssh_actions.SSHActionsTestsV2.test_run_ssh_proxied_action'
  - 'mistral_tempest_tests.tests.scenario.engine.actions.v2.test_openstack_actions.OpenStackActionsTestsV2.test_swift_actions'
  - 'mistral_tempest_tests.tests.scenario.engine.actions.v2.test_multi_vim_authentication.MultiVimActionsTests.test_multi_vim_support_target_headers'

undercloud_enable_paunch: false
