##################################################
# FEATURESET056 - TRIPLEO STANDALONE UPGRADE
##################################################

non_root_user_setup: true
ovb_setup_connectivity: false
package_installs: true
vxlan_networking: false

# role / scenario definition
# deployment role
standalone_role: Standalone.yaml

# docker / podman configuration
standalone_container_cli: podman

# NOTE(mwhahaha): we only care about ha -> ha upgrades. We switched to
# pacemaker enabled in Ussuri, so the upgrade from Train -> Ussuri is non-HA
# to HA. We should just test HA always in the upgrade
standalone_control_virtual_ip: 192.168.24.3
standalone_custom_env_files:
  - /usr/share/openstack-tripleo-heat-templates/environments/docker-ha.yaml

standalone_upgrade: true
# validation

test_ping: false

use_os_tempest: >-
  {% if release not in ['pike', 'queens', 'stein'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

test_regex: ''
# NOTE(aschultz): containers assume RC at the moment
tempest_undercloud: true
tempest_overcloud: false
tempest_os_cloud: standalone

tempest_whitelist:
  - 'tempest.scenario.test_minimum_basic.TestMinimumBasicScenario'
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps'
  - 'tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern'

tempest_test_whitelist: >-
  {{ tempest_whitelist }}

tempest_run_concurrency: 2
