undercloud_generate_service_certificate: false
ssl_overcloud: false
test_ping: true
deployed_server: true

composable_scenario: multinode.yaml
composable_services: false
# Use default test template
# validate_template: tenantvm-floatingip.yaml

composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant
