#### Summary of the feature set.
# Deploy an Openstack environment for testing FFU upgrade from Newton
# to Queen.  Based on featureset005 which is working on newton.
undercloud_generate_service_certificate: false
enable_opstools_repo: false

test_ping: false

use_os_tempest: false

test_white_regex: ''

deployed_server: true
composable_scenario: scenario002-multinode.yaml
upgrade_composable_scenario: scenario002-multinode-containers.yaml
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

mixed_upgrade: true

# Tripleo-upgrade link
ffu_overcloud_upgrade: true
tripleo_upgrade_validations_non_fatal: true

# disable tripleo-upgrade container manipulation.
create_docker_registry: false
use_local_docker_registry: false
create_container_images_download_script: false

# do not run workload test
launch_sanity_workload: false

tripleo_ci: true
use_oooq: true

# Run prep container before upgrade.
prep_container_upgrade_run: true
containerized_overcloud_upgrade: true
# container_registry_file is used pre-rocky, after rocky
# is uc_containers_prepare_file the one used to identify
# the containers file (defaults to: containers-prepare-parameter.yaml)
container_registry_file: containers-default-parameters.yaml

# Adjust user to CI
overcloud_ssh_user: "zuul"

# Workaround for deploying newton from queen.
overcloud_prep_post_hook_script: |
  cat > {{ overcloud_templates_path }}/plan-environment.yaml<<EOF
  version: 1.0

  name: overcloud
  description: >
    Default Deployment plan
  template: overcloud.yaml
  environments:
    - path: overcloud-resource-registry-puppet.yaml
  EOF

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-upgrade
    - overcloud-validate
