---
- name: Setup repos on live host
  shell: >
    set -o pipefail &&
    {{ repo_setup_dir }}/{{ repo_setup_script }} 2>&1 {{ timestamper_cmd }}
    | tee -a {{ repo_setup_dir }}/{{ repo_setup_log }}
  become: true
  register: result
  changed_when: true
  no_log: true
