---
driver:
  name: docker
log: true
platforms:

  # Warning: do not put pre-baked images for install-deps role because it will
  # fail to validate what happens on pure/clean systems.
  - name: centos7
    hostname: centos7
    image: centos:7
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"

  - name: centos8
    hostname: centos8
    image: centos:8
    environment: *env

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - destroy
