---
# For testing container-tools on centos-8-stream,
# we need to enable container-tools rhel8 module
# and disable container-tools 2.0 module.
# It will fetch latest podman and buildah

dependency_modules:
  - module_name: container-tools
    control_version: 2.0
    test_version: 3.0

dep_repo_cmd_after: |
  sudo dnf repolist;
  sudo dnf module list;
  {% for item in dependency_modules %}
  sudo dnf module disable {{ item.module_name }}:{{ item.control_version }} -y;
  sudo dnf module enable {{ item.module_name }}:{{ item.test_version }} -y;
  {% endfor %}
  sudo dnf clean metadata
  sudo dnf clean all;
  sudo dnf update -y;
