---
qemu_bridge_conf: /etc/qemu-kvm/bridge.conf
libvirt_packages:
  - qemu-kvm
  - libvirt
  - libvirt-python
  - libguestfs-tools
  - python-lxml
  - polkit-pkla-compat
  - python-netaddr

virtualbmc_packages:
  - python2-virtualbmc
