overcloud_as_undercloud: true
# limits validation on a specific enviroment due to restricted access
validate_on: rdo
images:
  - name: overcloud-full
    url: "{{ overcloud_image_url }}"
    type: tar
  - name: ipa_images
    url: "{{ ipa_image_url }}"
    type: tar
inject_images:
  - "ironic-python-agent.initramfs"
  - "ironic-python-agent.kernel"
  - "overcloud-full.qcow2"
  - "overcloud-full.initrd"
  - "overcloud-full.vmlinuz"
release: master
use_specific_hash: true
distro_ver: rhel8
distro_deps_repo_name: deps
dlrn_hash_tag: tripleo-ci-testing
delorean_hash_label: &promotion-testing-tag "{{ dlrn_hash|default(dlrn_hash_tag) }}"
dlrn_hash_tag_newest: current
docker_registry_host: trunk.registry.rdoproject.org
docker_registry_namespace: tripleomaster
docker_image_tag: *promotion-testing-tag
undercloud_docker_insecure_registries: "{{ docker_registry_host }}"
docker_prep_prefix: rhel-binary
docker_ceph_namespace: quay.ceph.io/ceph-ci
docker_openshift_tag: v3.11.0
overcloud_image_url: "https://images.rdoproject.org:4433/rcm-guest/images/redhat8/master/rdo_trunk/tripleo-ci-testing/overcloud-full.tar"
ipa_image_url: "https://images.rdoproject.org:4433/rcm-guest/images/redhat8/master/rdo_trunk/tripleo-ci-testing/ironic-python-agent.tar"

repo_cmd_before: |
  sudo rm -rf /etc/yum.repos.d/delorean*;
  sudo rm -rf /etc/yum.repos.d/*.rpmsave;
  {# dnf-plugins-core provides config-manager command #}
  sudo dnf install -y dnf-plugins-core;
  sudo dnf clean all;
  sudo dnf config-manager --set-disabled "*"
  if [ -e /etc/ci/mirror_info.sh ]; then
    source /etc/ci/mirror_info.sh
  else
    # Otherwise, fallback to RHEL8 dlrn trunk.
    export NODEPOOL_RDO_PROXY=https://trunk.rdoproject.org
  fi
  rdo_dlrn=`curl --silent ${NODEPOOL_RDO_PROXY}/{{ distro_ver }}-{{ release }}/{{ dlrn_hash_path|default(dlrn_hash_tag, true) }}/delorean.repo -S 2>>~/dlrn_repo_curl_errors.log | grep baseurl | cut -d= -f2`
  if [[ -z "$rdo_dlrn" ]]; then
    echo "Failed to parse dlrn hash"
    exit 1
  fi
  export RDO_DLRN_REPO=${rdo_dlrn/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}

repos:
  - type: generic
    reponame: delorean
    filename: delorean.repo
    priority: 20
    baseurl: $RDO_DLRN_REPO

  - type: generic
    reponame: "delorean-{{ release }}-deps"
    filename: "delorean-{{ release }}-deps.repo"
    baseurl: ${NODEPOOL_RDO_PROXY}/{{ distro_ver }}-{{ release }}/{{ distro_deps_repo_name }}/latest/

repo_cmd_after: |
  # TODO(chkumar246): Currently RHUI repos are disabled by default
  # Once it is fixed, it will remove this.
  sudo dnf config-manager --enable rhui-*;
  sudo dnf install -y chrony;
  sudo dnf install -y mock;
  sudo dnf install -y systemd-container;
  # TODO(chkumar246): Currently RHEL-8 mock DLRN config needs
  # /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT dummy file
  # in order to build packages,
  # https://softwarefactory-project.io/r/#/c/15950/
  sudo touch /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT;
  sudo dnf clean all;
  {% if repo_setup_run_update|default(true)|bool %}
  sudo dnf update -y;
  {% endif %}
  sudo dnf clean metadata

undercloud_rpm_dependencies: >-
  python3-tripleoclient
  ceph-ansible
overcloud_selinux_enabled: permissive
undercloud_selinux_enabled: false
