# Define a single controller node and a single compute node.
overcloud_nodes:
  - name: control_0
    flavor: control
    virtualbmc_port: 6230
    default_name: overcloud-controller-0
    hostnamemap_override: overcloud-controller-foo-0

  - name: compute_0
    flavor: compute
    virtualbmc_port: 6231
    default_name: overcloud-novacompute-0
    hostnamemap_override: overcloud-novacompute-bar-0

node_count: 2

# Tell tripleo which nodes to deploy.
topology_map:
  Controller:
    scale: 1
    networks:
      - network: ctlplane
        vif: true
      - network: external
        subnet: external_subnet
      - network: internal_api
        subnet: internal_api_subnet
      - network: storage
        subnet: storage_subnet
      - network: storage_mgmt
        subnet: storage_mgmt_subnet
      - network: tenant
        subnet: tenant_subnet
    network_config:
      template: templates/multiple_nics/multiple_nics_dvr.j2
      default_route_network:
        - external
  Compute:
    scale: 1
    networks:
      - network: ctlplane
        vif: true
      - network: internal_api
        subnet: internal_api_subnet
      - network: tenant
        subnet: tenant_subnet
      - network: storage
        subnet: storage_subnet
    network_config:
      template: templates/multiple_nics/multiple_nics_dvr.j2
