# Define a single controller node and two compute nodes.
overcloud_nodes:
  - name: control_0
    flavor: control
    virtualbmc_port: 6230
    default_name: overcloud-controller-0
    hostnamemap_override: overcloud-controller-foo-0

  - name: compute_0
    flavor: compute
    virtualbmc_port: 6231
    default_name: overcloud-novacompute-0
    hostnamemap_override: overcloud-novacompute-bar-0

  - name: compute_1
    flavor: compute
    virtualbmc_port: 6232
    default_name: overcloud-novacompute-1
    hostnamemap_override: overcloud-novacompute-bar-1

node_count: 3

topology_map:
  Controller:
    scale: 1
    networks:
      - network: ctlplane
        vif: true
      - network: external
        subnet: external_subnet
      - network: internal_api
        subnet: internal_api_subnet
      - network: storage
        subnet: storage_subnet
      - network: storage_mgmt
        subnet: storage_mgmt_subnet
      - network: tenant
        subnet: tenant_subnet
  Compute:
    scale: 2
    networks:
      - network: ctlplane
        vif: true
      - network: internal_api
        subnet: internal_api_subnet
      - network: tenant
        subnet: tenant_subnet
      - network: storage
        subnet: storage_subnet
