overcloud_nodes:
  - name: control_0
    flavor: control
    default_name: overcloud-controller-0
    hostnamemap_override: "{{ hostvars[groups['overcloud'][0]].ansible_hostname }}"
  - name: control_1
    flavor: control
    default_name: overcloud-two-controller-0
    hostnamemap_override: "{{ hostvars[groups['overcloud'][1]].ansible_hostname }}"

node_count: 2

deployed_server_overcloud_roles:
  - name: Controller
    hosts: "$(sed -n 1,1p /etc/nodepool/sub_nodes_private)"

topology_map:
  Controller:
    scale: 2
    networks:
      - network: ctlplane
        vif: true
      - network: external
        subnet: external_subnet
      - network: internal_api
        subnet: internal_api_subnet
      - network: storage
        subnet: storage_subnet
      - network: storage_mgmt
        subnet: storage_mgmt_subnet
      - network: tenant
        subnet: tenant_subnet
    network_config:
      template: templates/multiple_nics/multiple_nics_dvr.j2
      default_route_network:
        - external
  Compute:
    scale: 0
