# This config file is used to deploy a HA overcloud with a dedicated node on the virthost for TLS everywhere.

# Define the controller node and compute nodes.
# Create three controller nodes and one compute node.
node_count: 4

overcloud_nodes:
  - name: control_0
    flavor: control
    virtualbmc_port: 6230

  - name: control_1
    flavor: control
    virtualbmc_port: 6231

  - name: control_2
    flavor: control
    virtualbmc_port: 6232

  - name: compute_0
    flavor: compute
    virtualbmc_port: 6233

# Define the supplmental node to be used for the FreeIPA server.
supplemental_node:
  name: ipa
  flavor: undercloud

topology_map:
  Controller:
    scale: 3
    networks:
      - network: ctlplane
        vif: true
      - network: external
        subnet: external_subnet
      - network: internal_api
        subnet: internal_api_subnet
      - network: storage
        subnet: storage_subnet
      - network: storage_mgmt
        subnet: storage_mgmt_subnet
      - network: tenant
        subnet: tenant_subnet
    network_config:
      template: templates/multiple_nics/multiple_nics_dvr.j2
      default_route_network:
        - external
  Compute:
    scale: 1
    networks:
      - network: ctlplane
        vif: true
      - network: internal_api
        subnet: internal_api_subnet
      - network: tenant
        subnet: tenant_subnet
      - network: storage
        subnet: storage_subnet
    network_config:
      template: templates/multiple_nics/multiple_nics_dvr.j2
