# Deploy an HA openstack environment.

# Three controller nodes and one compute node are defined
# hardware-specific files
overcloud_nodes:

node_count: 5

# Tell tripleo which nodes to deploy.
topology_map:
  Controller:
    scale: 3
    networks:
      - network: ctlplane
        vif: true
      - network: external
        subnet: external_subnet
      - network: internal_api
        subnet: internal_api_subnet
      - network: storage
        subnet: storage_subnet
      - network: storage_mgmt
        subnet: storage_mgmt_subnet
      - network: tenant
        subnet: tenant_subnet
    network_config:
      template: templates/multiple_nics/multiple_nics_dvr.j2
      default_route_network:
        - external
  Compute:
    scale: 2
    networks:
      - network: ctlplane
        vif: true
      - network: internal_api
        subnet: internal_api_subnet
      - network: tenant
        subnet: tenant_subnet
      - network: storage
        subnet: storage_subnet
    network_config:
      template: templates/multiple_nics/multiple_nics_dvr.j2
