---
# vars required to run playbooks/libvirt-nodepool.yml

libvirt_volume_pool: oooq_pool
libvirt_volume_path: /opt/vm_images
libvirt_uri: qemu:///system
overcloud_nodes:
  - name: subnode-0
    flavor: control

  - name: subnode-1
    flavor: control
pub_key: "~/.ssh/id_rsa.pub"
image_fetch_dir: "{{ local_working_dir }}"
libvirt_nodepool_vms: true
create_instackenv_json: false
vm_pass: random
control_vcpu: 6
control_memory: 16384
images:
  - name: centos
    url: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2
    type: qcow2
    md5sum: "bf653cc2b5becb29c6cf7c6f7ecaf70f  CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2"
libvirt_wait_retries: 30
libvirt_wait_delay: 20
